Repository napari-phasors/napari-phasors, pull requests merged in 2024-11, with the labels that each got.

#48 Add defaults to ptu and fbd reader widgets.
  src/napari_phasors/_widget.py
Labels: enhancement

#51 Change Hist2D plot background to white
  setup.cfg
  src/napari_phasors/plotter.py
Labels: enhancement

#58 Add reader for '.sdt' files and widget for phasor transform
  src/napari_phasors/_reader.py
  src/napari_phasors/_tests/test_reader.py
  src/napari_phasors/_tests/test_widget.py
  src/napari_phasors/_widget.py
  src/napari_phasors/napari.yaml
Labels: enhancement

#59 Fix advanced options
  src/napari_phasors/plotter.py
  src/napari_phasors/ui/plotter_inputs_widget_extra.ui
Labels: bug

#56 Add Lifetime Widget and lifetime colormap
  src/napari_phasors/__init__.py
  src/napari_phasors/_tests/test_widget.py
  src/napari_phasors/_utils.py
  src/napari_phasors/_widget.py
  src/napari_phasors/napari.yaml
  src/napari_phasors/plotter.py
Labels: enhancement

#65 Add initial sample data
  src/napari_phasors/__init__.py
  src/napari_phasors/_sample_data.py
  src/napari_phasors/_tests/test_reader.py
  src/napari_phasors/_tests/test_sample_data.py
  src/napari_phasors/_tests/test_widget.py
  src/napari_phasors/_widget.py
  src/napari_phasors/napari.yaml
  src/napari_phasors/plotter.py
Labels: enhancement

#73 Export settings and Read setting from OME-TIF
  src/napari_phasors/_reader.py
  src/napari_phasors/_tests/test_reader.py
  src/napari_phasors/_tests/test_widget.py
  src/napari_phasors/_utils.py
  src/napari_phasors/_widget.py
  src/napari_phasors/_writer.py
  src/napari_phasors/plotter.py
Labels: enhancement

#71 Documentation
  .github/workflows/run-tests.yml
  LICENSE
  README.md
Labels: documentation

#74 Change setting saved as JSON format
  src/napari_phasors/_reader.py
  src/napari_phasors/_tests/test_writer.py
  src/napari_phasors/_utils.py
  src/napari_phasors/_widget.py
  src/napari_phasors/_writer.py
Labels: bug

#75 Include UI folder in build release.
  LICENSE
  MANIFEST.in
  setup.cfg
Labels: bug

#76 Bump version to 0.0.2
  src/napari_phasors/__init__.py
Labels: documentation
